[package]
name = "router"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = { path = "../http" }

[dependencies.async-std]
version = "1.6"
features = ["attributes"]